import { jsPDF } from 'jspdf';
import { Storyboard } from '@/types/storyboard';

export async function exportToPdf(storyboard: Storyboard): Promise<void> {
  const pdf = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - 2 * margin;

  // Title
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text(storyboard.title || 'Untitled Storyboard', margin, margin + 10);

  // Description
  if (storyboard.description) {
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100);
    const descLines = pdf.splitTextToSize(storyboard.description, contentWidth);
    pdf.text(descLines, margin, margin + 20);
    pdf.setTextColor(0);
  }

  let yPosition = margin + 35;

  // Style notes
  if (storyboard.styleNotes) {
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'italic');
    pdf.setTextColor(80);
    const styleLines = pdf.splitTextToSize(`Style: ${storyboard.styleNotes}`, contentWidth);
    pdf.text(styleLines, margin, yPosition);
    yPosition += styleLines.length * 4 + 5;
    pdf.setTextColor(0);
  }

  // Panels
  const panelWidth = (contentWidth - 10) / 3;
  const panelHeight = panelWidth * 0.75;
  const panelsPerRow = 3;
  const panelGap = 5;

  for (let i = 0; i < storyboard.panels.length; i++) {
    const panel = storyboard.panels[i];
    const row = Math.floor(i / panelsPerRow);
    const col = i % panelsPerRow;
    
    const panelX = margin + col * (panelWidth + panelGap);
    const panelY = yPosition + row * (panelHeight + 30);

    // Check if we need a new page
    if (panelY + panelHeight + 20 > pageHeight) {
      pdf.addPage();
      yPosition = margin;
    }

    // Panel number and description
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`Panel ${i + 1}`, panelX, panelY);

    // Panel box
    pdf.setDrawColor(200);
    pdf.setLineWidth(0.3);
    pdf.rect(panelX, panelY + 3, panelWidth, panelHeight);

    // Panel image or placeholder
    if (panel.imageUrl) {
      try {
        const imgData = await loadImageAsBase64(panel.imageUrl);
        if (imgData) {
          pdf.addImage(imgData, 'JPEG', panelX + 1, panelY + 4, panelWidth - 2, panelHeight - 2);
        } else {
          pdf.setFontSize(8);
          pdf.setFont('helvetica', 'normal');
          pdf.text('Image not available', panelX + panelWidth / 2, panelY + panelHeight / 2 + 3, { align: 'center' });
        }
      } catch {
        pdf.setFontSize(8);
        pdf.setFont('helvetica', 'normal');
        pdf.text('Image load failed', panelX + panelWidth / 2, panelY + panelHeight / 2 + 3, { align: 'center' });
      }
    } else {
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'normal');
      pdf.text('No image', panelX + panelWidth / 2, panelY + panelHeight / 2 + 3, { align: 'center' });
    }

    // Scene description
    const descY = panelY + panelHeight + 8;
    if (panel.sceneContent.description) {
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'normal');
      const descLines = pdf.splitTextToSize(panel.sceneContent.description, panelWidth);
      pdf.text(descLines.slice(0, 2), panelX, descY);
    }

    // Dialogue
    const dialogueY = descY + 8;
    if (panel.sceneContent.dialogue) {
      pdf.setFontSize(7);
      pdf.setFont('helvetica', 'italic');
      const dialogueText = `"${panel.sceneContent.dialogue}"`;
      const dialogueLines = pdf.splitTextToSize(dialogueText, panelWidth);
      pdf.text(dialogueLines.slice(0, 2), panelX, dialogueY);
    }
  }

  // Footer
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(150);
  pdf.text(
    `Generated by AI Storyboard • ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  // Save
  const filename = `${storyboard.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_storyboard.pdf`;
  pdf.save(filename);
}

async function loadImageAsBase64(url: string): Promise<string | null> {
  try {
    const response = await fetch(url);
    const blob = await response.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}
